# Generated by Django 5.0.3 on 2024-03-19 17:42

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_alter_person_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Описание изображения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Файл с изображением')),
            ],
            managers=[
                ('obj_img', django.db.models.manager.Manager()),
            ],
        ),
    ]
