# Generated by Django 5.0.3 on 2024-03-20 16:23

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Описание видеофайла')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos', verbose_name='Видеофайл')),
            ],
            managers=[
                ('obj_video', django.db.models.manager.Manager()),
            ],
        ),
    ]
